### ISSUE TITLE
Question about uniqueness quantification

### ISSUE THREAD

**Issue by ersincine** [stepchowfun/theorem-prover#5]
Thank you for this useful program.

Is there a way to represent formulas with uniqueness quantifier such as **∃!xP(x)** ≡ ∃x(P(x)∧∀y(P(y)→y=x))?

**Comment by stepchowfun** [comment]
Hi @ersincine, this tool doesn't have any built-in notion of equality. So you'd have to add a few equality axioms. Then you could express what you want, I believe.

Something like:

```
axiom forall x. Equals(x, x)
axiom forall x. forall y. Equals(x, y) implies Equals(y, x)
axiom forall x. (Equals(x, y) and Equals(y, z)) implies Equals(x, z)
```

I didn't test that, though. I haven't touched this repo in years. 😋

**Comment by ersincine** [comment]
Great answer. Thank you very much.

BTW, I realized that [a fork](https://github.com/teknomo/theorem-prover) has already implemented the build-in function Equals(x, y).

**Comment by stepchowfun** [comment]
Oh wow, I haven't seen that before. Thanks for sharing it! I'll close this issue now.
